source 'http://rubygems.org'
gem 'iconv'
gem 'padrino','0.10.7'
gem 'padrino-core','0.10.7'
gem 'sinatra',"1.3.1"
gem 'sinatra-xsendfile'
gem 'sinatra-reloader'
gem 'mechanize'
gem 'rack',"1.4.1"
gem 'mongoid',"2.3.0"
gem 'mongo',"1.7.0"
gem 'bson',"1.7.0"
gem 'bson_ext',"1.7.0"
gem 'ruby-mp3info'
gem 'unicorn'
#gem 'mecab-ruby'
gem 'taglib-ruby'
gem 'taglib2'
#gem 'MeCab'
gem 'mecab'
gem 'ruby-taglib2'
#gem 'MeCab' from source 
gem 'ruby-audioinfo'
gem 'puma'
